

GET https://bgu7c83m9f.execute-api.us-west-2.amazonaws.com/prod/spaces/
###

POST https://bgu7c83m9f.execute-api.us-west-2.amazonaws.com/prod/spaces/
Content-Type: application/json

{
    "location": "Paris"
}
###

GET https://bgu7c83m9f.execute-api.us-west-2.amazonaws.com/prod/spaces
###
