

GET https://bgu7c83m9f.execute-api.us-west-2.amazonaws.com/prod/spaces/
###
 
POST https://bgu7c83m9f.execute-api.us-west-2.amazonaws.com/prod/spaces/
Content-Type: application/json

{
    "location": "Minneapolis test"
}
###

GET https://bgu7c83m9f.execute-api.us-west-2.amazonaws.com/prod/spaces?id=d6688b82-b063-47a3-afc6-6eb7831b3931
###

PUT https://bgu7c83m9f.execute-api.us-west-2.amazonaws.com/prod/spaces?id=d6688b82-b063-47a3-afc6-6eb7831b3931
Content-Type: application/json

{
    "location": "Minneapolis1"
}
###

DELETE https://bgu7c83m9f.execute-api.us-west-2.amazonaws.com/prod/spaces?id=d6688b82-b063-47a3-afc6-6eb7831b3931
###